using System;

namespace Moos.Framework.Controls.SourceGen
{
   // [Generator(LanguageNames.CSharp)]
    public class CodeBehindGenerator 
    { 
        const string AutoGeneratedHeaderText = @"
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a .NET MOOS source generator.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        ";

        public void Initialize()
        { 
        }

        static string EscapeIdentifier(string identifier)
        {
            return "";
        }
    }
}
