namespace MoosApplication 
{
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Moos.Framework.Controls;
using Moos.Framework.Data;
using System;
using System.Windows;
using System.Windows.Controls;
using System.Xaml;



public partial class MainWindow : Moos.Framework.Controls.Window {
    
    private System.Globalization.CultureInfo EnglishCultureInfo = new System.Globalization.CultureInfo("en-us", false);
    
    public Moos.Framework.Controls.Button btnClick;
    
    public void InitializeComponent() {
        this.Title = "Moos Xaml";
        this.Height = 450;
        this.Width = 600;
        // ---------------------------
        Grid _grid0 = new Grid();
        // ---------------------------
        UIElementCollection _uIElementCollection1 = _grid0.Children;
        // ---------------------------
        btnClick = new Button();
        ThicknessConverter _thicknessConverter = new ThicknessConverter();
        btnClick.Margin = ((Thickness)(_thicknessConverter.ConvertFrom(null, EnglishCultureInfo, "5")));
        btnClick.Text = "Click me!";
        EventConverter _eventConverter = new EventConverter();
        btnClick.Click = ((EventHandler)(_eventConverter.ConvertFrom(null, EnglishCultureInfo, "onClick")));
        // ---------------------------
        Binding _binding2 = new Binding("");
        _binding2.Source = OnCounterClicked;
        btnClick.SetBinding(Moos.Framework.Controls.Button.CommandProperty, _binding2);
        _uIElementCollection1.Add(btnClick);
        this.Content = _grid0;
    }
}

}
