//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Moos.Framework.Controls;
using System;
using System.Windows.Controls;



public partial class UIMainWindow : System.Windows.Window {
    
    private System.Globalization.CultureInfo EnglishCultureInfo = new System.Globalization.CultureInfo("en-us", false);
    
    public UIMainWindow() {
        this.Title = "Moos Xaml";
        this.Height = 200D;
        this.Width = 200D;
        // ---------------------------
        Grid _grid0 = new Grid();
        this.Content = _grid0;
    }
}
